## Optimising Price of the Products

#### Importing libraries

In [1]:
import pandas as pd
import numpy as np

#### Importing the dataset

In [2]:
df = pd.read_csv('Vendor_Data.csv')

#### Details

In [3]:
df.head()

,Products,Avg_Price_per_unit,Cost_per_unit,Average_Profit_per_unit,Average_units_sold,Incremental_acquisition,Increase_sale_volume
0,Product 1,95,92,2.8,0.6,0.00323,0.08906
1,Product 2,37,27,10.0,0.8,0.00106,0.01991
2,Product 3,34,26,8.5,0.6,0.00328,0.03778
3,Product 4,32,30,2.8,0.7,0.00000,0.08562
4,Product 5,62,45,16.0,1.0,0.00079,0.02637

In [4]:
df.describe()

,Avg_Price_per_unit,Cost_per_unit,Average_Profit_per_unit,Average_units_sold,Incremental_acquisition,Increase_sale_volume
count,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000
mean,60.620000,51.596000,9.034400,1.500400,0.001366,0.050986
std,28.318959,24.182223,7.433913,0.839511,0.001579,0.029084
min,10.000000,9.000000,0.000000,0.100000,0.000000,0.000370
25%,37.000000,32.000000,3.100000,0.800000,0.000000,0.025528
50%,57.000000,50.500000,7.150000,1.400000,0.000690,0.051620
75%,85.750000,71.750000,12.975000,2.200000,0.002560,0.076580
max,110.000000,105.000000,29.700000,3.100000,0.006150,0.099430

#### Initial profit:

In [5]:
initial_profit = 0.05*(np.sum(df["Avg_Price_per_unit"]*df["Average_units_sold"])
                       - np.sum(df['Cost_per_unit']*df["Average_units_sold"]))
print(initial_profit)

164.2949999999999

#### This function will get us the overall revenue for the given increment vector

In [6]:
def find_rev(increment):
    price = df['Avg_Price_per_unit']*(1+increment)
    volumes = df['Average_units_sold']*(1-(df['Increase_sale_volume']*increment*10))
    multiplier = (1-(df['Incremental_acquisition']*increment*10))
    total_multiplier = np.prod(multiplier)
    profit_wo_multiplier = 0.05*(np.sum(price*volumes) - np.sum(volumes*df['Cost_per_unit']))
    profit_w_multiplier = profit_wo_multiplier*total_multiplier
    net_profit = np.sum(profit_w_multiplier)
    return net_profit

#### This function tries to get the next best increment vector

In [7]:
def incremental_new(initial_increments):
    initial_rev = find_rev(initial_increments)
    intermediate_rev = 0
    for i in range(250):
        increments = initial_increments
    
        if increments[i] > -0.099:
            increments[i] = increments[i] - 0.01
            rev = find_rev(increments)
            if rev > initial_rev:
                final_increments = increments
                intermediate_rev = rev
            else :
                increments[i] = increments[i] + 0.01
                
        if increments[i] < 0.20:
            increments[i] = increments[i] + 0.01
            rev = find_rev(increments)
            if rev > max(initial_rev, intermediate_rev):
                final_increments = increments
            else:
                increments[i] = initial_increments[i] - 0.01
    
    final_increments = increments
    
    return final_increments

#### This loop will get the maximum value of profit and the increment % in price

In [8]:
# This is the initial value of the increment vector - all zeros
increment_i = np.repeat(0.0,250)

#flag = 1 is a condition when the find_rev() function start giving same prfit
flag = 0
check = [0.0]
while flag==0:
    print(find_rev(increment_i))
    increment_iplus1 = incremental_new(increment_i)
    if (find_rev(increment_i) == max(check)):
        flag = 1
    check.append(find_rev(increment_i))
    increment_i = increment_iplus1

164.2949999999999
166.16997980393856
168.02512735101925
169.85826254457677
171.6670875344701
173.45099155922586
175.21138764500262
176.94674470135556
178.65780245247052
180.53061637456804
182.38675908276085
182.55238967675024
183.56506827935527
183.69598767298444
184.71833746333337
184.87518739837435
186.08844576579506
186.20229192405804
187.42415376610757
187.55294181101624
188.76986039769838
188.8670013681273
189.9957542599654
190.08906730162582
191.22631959089233
191.34302390743218
192.4894248953547
192.61514660045418
193.70193388875333
193.8619363542867
194.9307927069306
195.04733023482174
195.87168717847885
195.96168168683892
196.79243096070985
196.9122643013736
197.74967069855876
197.8679881445261
198.71235536344687
198.79491141767758
199.64566299956516
199.75967424697095
200.61623840840156
200.7292010359817
201.5921766967817
201.69880096596606
202.64851440340422
202.75820024736916
203.71229751905824
203.8087326049062
204.7700762920736
204.86058692617794
205.8183013829264
205.9059549285669
206.86320736732955
206.96011490716043
207.91820200431374
208.0461192454327
208.98569823968538
209.12924335018548
210.06971751298553
210.20701944482047
211.14684394775114
211.28096440415663
212.20850279377655
212.36857579602082
213.28583883250695
213.42339350802098
214.3409268996012
214.46831436270602
215.35678056559507
215.48742085075185
216.37718881684256
216.49939265653498
217.26594729296977
217.3816588056104
218.1235503275675
218.25328626185794
219.1214054006793
219.2400177807446
220.09512838004156
220.21078477150925
220.9131867277766
221.15286332951527
221.8530195440398
222.01420449579797
222.74043559454654
222.88982114642246
223.51044922138007
223.69546780350672
224.34694386597926
224.49856465640127
225.1492912402556
225.32222177083048
225.97230277839904
226.135856803117
226.86242632415832
227.02864944960885
227.68452615229123
227.8677671622063
228.56908964042674
228.73299949699344
229.4080061766282
229.57239096496767
230.18914489592825
230.3536834450432
230.9691056437597
231.12857110780848
231.72308922558133
231.87942646676296
232.56766321178597
232.7434923060974
233.3059595415727
233.48071557960614
234.11484259472795
234.30398135304821
234.93523045157892
235.0908605563222
235.80043320211402
235.95376000855856
236.47695969851057
236.6493503691946
237.07997334402324
237.24521839152894
237.64918822747316
237.82573983020106
238.34811470133727
238.57657590707328
238.97681843210992
239.20148700289002
239.59988613414785
239.767868413702
240.1643048070147
240.38614075677958
240.77699354818105
240.8953415133272
241.4035410594696
241.59126357463447
242.04026994476732
242.2148423624922
242.60492338559882
242.79490636881695
243.17635675353745
243.36461342026078
243.83733866128185
244.00329235342332
244.31978729193315
244.5136333956461
244.8507030622878
244.9700635092756
245.25979320730787
245.4927258893808
245.79070893007858
245.90964365838445
246.26501647287375
246.5000632894485
246.8541093639634
247.08962029040242
247.38828056510525
247.62338034575836
247.92065620479366
248.15050667332648
248.44638069416405
248.6369230751968
248.93140970649506
249.11003290662308
249.50119065120708
249.61679306144467
249.89104063850107
250.00874000647605
250.2806865938269
250.47302097238762
250.75193674430437
250.93624074701373
251.15812198394673
251.34804713672554
251.56735897150148
251.74826949195756
252.01616448487167
252.24861730716438
252.52938484102265
252.68632084556808
252.96238888742243
253.14516393189297
253.41592261560373
253.57397761869294
253.8677877886516
254.01813080487543
254.32484022785405
254.465035363798
254.66872686029157
254.8166282823028
255.1078115074503
255.22940555311635
255.4308324771506
255.5492083003487
255.74918923320254
255.91728113737867
256.10526976665443
256.2598022951287
256.4570086330184
256.5818605821835
256.7778080896791
256.92341121105477
257.10577875471904
257.2552561560933
257.5334872585751
257.67733635786806
257.8365949528809
257.96007578957335
258.162991328502
258.29272833147303
258.49216084319727
258.6178009064059
258.7906881566751
258.913718893272
259.085647055029
259.23536639022586
259.526606870371
259.69786048956973
259.8393053922316
259.99703240116617
260.137202046206
260.2921712098203
260.43480631650266
260.5819045291995
260.723322111769
260.86419923642626
261.0104446747172
261.1739616202884
261.318144327293
261.46359870327956
261.6263529103006
261.75670755552915
261.9158683871841
262.0831974568264
262.23871491375013
262.4011949035533
262.5530003147523
262.69165810927996
262.83960720807414
262.9851517137176
263.1540949973031
263.30959297635314
263.4830274843701
263.6434443330562
263.78319677226654
263.9445605427835
264.1909095094319
264.32263121038557
264.56660128288433
264.73414137820623
264.9759022586818
265.14711652118893
265.3238789543893
265.475946208893
265.74626349765896
265.91405169589916
266.0850593834908
266.2571641711589
266.42535173634985
266.55777886822096
266.72307595598846
266.8979798453903
267.0372262944362
267.17216610685375
267.3410740293482
267.48381231678223
267.6461572986133
267.8618302785273
268.09141820016004
268.28710674770826
268.45775497967173
268.5852366098506
268.75380437527707
268.87705922516017
269.0436144364199
269.1698030997579
269.371873343737
269.49599637237526
269.6467105330943
269.82065936936004
270.0751744801406
270.265335943212
270.51543082747077
270.69637890264613
270.89280841249206
271.078964774377
271.3114132882992
271.4971407864341
271.6504740086888
271.8174852059524
271.999530814817
272.1258283094524
272.36010737264786
272.4833729029631
272.7145085355571
272.8371869527899
273.06659651442334
273.19455499472286
273.32823475021735
273.5023424243325
273.63281149439575
273.79969566582207
273.98290311155574
274.1043214242858
274.2352442142974
274.40564289626565
274.5848818079876
274.7469426695707
274.9222042912773
275.0450647675241
275.26857800281454
275.43974998401205
275.6594408619568
275.83553253366927
276.0514994404697
276.227899589385
276.416361807385
276.52626568035816
276.6893168913252
276.82705219648557
276.9860144300148
277.12093627933285
277.2631868329628
277.4841339634274
277.63860705499764
277.8529622756218
278.01453315345384
278.1275983294968
278.3318363128074
278.4565771033019
278.6498104782278
278.7762502145323
278.9126610998337
279.068669998116
279.1982269134552
279.3255508651255
279.53795687684453
279.71300180004584
279.94901085303565
280.10781555248053
280.3403355299474
280.49413609937574
280.6998927764065
280.8469494357456
281.07772705624336
281.26019276901906
281.443313964221
281.56218116153264
281.7393555254796
281.9174842563748
282.1456119643888
282.2636999667312
282.4949726293989
282.65969971681335
282.8913103947112
283.0620159629032
283.2901288317753
283.4747575440372
283.6979013113549
283.8823937285465
284.0791968757969
284.2634520620251
284.3811654873234
284.5651436859156
284.6789489174486
284.80210846509505
284.9139591846277
285.0718672770695
285.1822805084722
285.3391546499824
285.46575151743946
285.5783622030685
285.6931425962144
285.87806095478123
286.0471792958965
286.2003180087249
286.327085717073
286.4772477715005
286.64108474941133
286.78828328464573
286.91303805635727
287.05011022323345
287.1737268090823
287.3225631907282
287.48516739137796
287.636963699117
287.7946520961445
287.9437842212442
288.1048191126026
288.2881801604752
288.42017665832014
288.5656856546083
288.6941264134528
288.85698138271147
288.996606098104
289.18513690512515
289.37468047956287
289.5620974326686
289.74235498887566
289.87976941829146
290.0099180708491
290.21026123884417
290.3287870387912
290.46514162914383
290.5879166235385
290.72384977627394
290.84091735783454
291.0369173005571
291.14808741684186
291.29614074856187
291.40221791406884
291.5842247074681
291.76712260132746
291.92702850307705
292.0343526317821
292.1940023519993
292.3015331203695
292.4603365452826
292.654413258687
292.82975616446794
292.96923101180204
293.10664089810626
293.21184274619026
293.3954899885475
293.58252094268454
293.76589758152505
293.87866784006064
294.0532132107801
294.2476184995366
294.4218655136619
294.61304171630746
294.7843567358272
294.92408568857815
295.0100681594815
295.19570202675897
295.28836584646575
295.47881005708246
295.57235082768915
295.76509821203183
295.89202516687243
296.0273756840518

296.15275490462466
296.2866563931514
296.4104726114873
296.5427945413461
296.6467000993984
296.81831953880175
296.9752659398491
297.10758531718005
297.18826614620485
297.31862531345723
297.4306665853337
297.5606019480643
297.71940808920255
297.8733846506911
298.02019380056043
298.19386022351824
298.3392008158242
298.4768036443051
298.5853754983943
298.73911978844217
298.8847762843347
299.01581056900454
299.1934590465525
299.3303360813239
299.4206939672583
299.5453823629106
299.6925479583293
299.8166729766849
299.9077949596034
300.0440028200275
300.20511809246375
300.32871157310467
300.49778955234154
300.6329348087788
300.7852847307732
300.9204701741028
300.99977748855287
301.12309066136845
301.233358393774
301.3773102210478
301.4786213094532
301.6110210387281
301.71923574005956
301.85269052967766
301.96532358829865
302.06146048629705
302.1589046395256
302.2404117799579
302.3219403378163
302.4345838501601
302.50073826929116
302.632103565358
302.6811502278137
302.82871356521736
302.92759085925627
303.0557677787572
303.1487089693291
303.2564374612261
303.3569402400209
303.4872531292766
303.5248230078494
303.61655864942264
303.70432974104614
303.76944519380106
303.83813783144507
303.9518371056572
304.0179673126074
304.1313914003468
304.18821989905
304.26046403544706
304.30737179897943
304.3759513391987
304.42028499567743
304.4943464988369
304.5361919526026
304.59397203708494
304.65675696890776
304.742301016585
304.79258424811775
304.86488566100144
304.92126036786675
304.98952900876174
305.02716287682273
305.09064906870236
305.15213233276836
305.20984309613334
305.25269221389055
305.33219779829534
305.3678984172691
305.4255382977458
305.45880744991604
305.51367648690547
305.5454999485103
305.59896489668995
305.62981989058136
305.6818811478543
305.71177319785863
305.76244464782707
305.79135855577715
305.86451713282617
305.90472785829917
305.9750649286912
306.0144941739326
306.08206100674386
306.12066023414474
306.194404501365
306.23220479465107
306.29743837360246
306.3344515828274
306.4120703278571
306.4632353027136
306.5395474711543
306.56997296597757
306.6254352747869
306.6542933927037
306.7082529045796
306.7355817334208
306.78797778821473
306.8137524963963
306.8646092702879
306.88885547830694
306.9381804944772
306.96086788958746
307.00865244160485
307.02978599560055
307.10915754560875
307.1616587556107
307.23910256541603
307.2896468798933
307.3447085046587
307.38682055976767
307.4527207437742
307.4904432944063
307.5519937735233
307.5853343101685
307.64257195617887
307.671569083886
307.72450169716166
307.7491825211815
307.79777961662563
307.8150593902606
307.8582612669448
307.8622834793571
307.89222409927675
307.8958288410762
307.9253689272925
307.9285670033531
307.9576853054084
307.9604659300215
307.989172836248
307.99153608807916
308.0198315198112
308.02177747752637
308.0496613560974
308.0511900983624
308.0786623451073
308.079773950588
308.1068344868406
308.1075290342023
308.1341777812972
308.13445534920584
308.16069222847756

#### Adding the optimum value in the dataset

In [9]:
df['Opt_Price'] = np.around(increment_i,2)
df.head()

,Products,Avg_Price_per_unit,Cost_per_unit,Average_Profit_per_unit,Average_units_sold,Incremental_acquisition,Increase_sale_volume,Opt_Price
0,Product 1,95,92,2.8,0.6,0.00323,0.08906,-0.1
1,Product 2,37,27,10.0,0.8,0.00106,0.01991,-0.1
2,Product 3,34,26,8.5,0.6,0.00328,0.03778,-0.1
3,Product 4,32,30,2.8,0.7,0.00000,0.08562,0.2
4,Product 5,62,45,16.0,1.0,0.00079,0.02637,0.2

#### Exporting updated file in CSV format

In [10]:
df.to_csv("Update_Vendor_Data.csv",index=False)

#### optimized_profit:

In [11]:
Optimum_profit = max(check)
print(np.around(Optimum_profit,2))

308.16

In [12]:
df.head()

,Products,Avg_Price_per_unit,Cost_per_unit,Average_Profit_per_unit,Average_units_sold,Incremental_acquisition,Increase_sale_volume,Opt_Price
0,Product 1,95,92,2.8,0.6,0.00323,0.08906,-0.1
1,Product 2,37,27,10.0,0.8,0.00106,0.01991,-0.1
2,Product 3,34,26,8.5,0.6,0.00328,0.03778,-0.1
3,Product 4,32,30,2.8,0.7,0.00000,0.08562,0.2
4,Product 5,62,45,16.0,1.0,0.00079,0.02637,0.2

#### Difference in profit

In [16]:
profit_difference = Optimum_profit - initial_profit 
print(profit_difference)

143.86569222847766